#!/usr/bin/env bash
# transfer a file from our client to a server

if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~
fi;
