#!/usr/bin/env bash
# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Hosts file to set localhost to 127.0.0.2 and facebook.com to 8.8.8.8
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
} | sudo tee -a /etc/hosts >/dev/null
